"""Turn campaign results into the fault coverage report.

This module makes the judgements the campaign deliberately refused to make. The
campaign records what the device did; the report decides whether that met the
budget. Keeping them apart means a changed FTTI re-judges existing run data
instead of requiring a fresh campaign, which is the difference between evidence
and a pass/fail script.

Two things it is careful never to claim:

  It reports DETECTION COVERAGE OVER THE INJECTED FAULT SET, which is a
  statement about this catalog. It is not diagnostic coverage in the ISO 26262
  sense: that needs an FMEDA with component failure rates in FIT, and there are
  none here. The two get conflated constantly and an assessor checks.

  Latencies are in SIMULATION STEPS. The DUT advances in steps, and its thermal
  time scale is deliberately compressed, so converting to seconds would invent
  precision that does not exist.
"""

from __future__ import annotations

from collections import defaultdict

from fih.campaign import RunResult
from fih.catalog import Fault
from fih.dual_point import Pair, PairResult
from fih.dual_point import verdict as verdict_pair
from fih.protected_campaign import ProtectedResult
from fih.traceability import Requirement, check


def verdict(fault: Fault, result: RunResult) -> tuple[bool, str]:
    """Did this fault meet its requirement? Returns (ok, explanation)."""
    if fault.is_residual:
        # A residual fault PASSES by remaining undetected. If one is suddenly
        # caught, the design changed and the rationale is stale, so that is a
        # failure too: the report must not quietly absorb good news either.
        if result.detected:
            return False, ("expected residual but the design detected it; the "
                           "recorded rationale is now stale")
        return True, "residual as documented"

    if not result.detected:
        return False, "not detected"

    latency = result.detected_at_step
    if fault.is_late:
        # A LATE fault passes by being late, exactly as a residual one passes by
        # being undetected. The verdict records that the design behaved as
        # documented; it does NOT record that the requirement was met, and the
        # traceability matrix is where that distinction is enforced.
        assert fault.ftti_steps is not None
        if latency is None or latency <= fault.ftti_steps:
            return False, ("expected detection outside the budget but it came in "
                           "on time; the recorded rationale is now stale")
        return True, (f"detected at {latency} steps, OUTSIDE the "
                      f"{fault.ftti_steps} step budget, as documented")
    if latency is None:
        # Rejected on arrival, which is detection at the protocol boundary
        # before any step elapsed.
        return True, "rejected on arrival (0 steps)"

    assert fault.ftti_steps is not None
    if latency > fault.ftti_steps:
        return False, f"detected at {latency} steps, over the {fault.ftti_steps} budget"
    return True, f"detected at {latency} of {fault.ftti_steps} steps"


def build(faults: tuple[Fault, ...], results: dict[str, RunResult],
          requirements: tuple[Requirement, ...]) -> tuple[str, bool]:
    """Render the report. Returns (markdown, all_ok)."""
    mapping = check(faults, requirements)
    by_id = {f.id: f for f in faults}

    verdicts = {f.id: verdict(f, results[f.id]) for f in faults}
    all_ok = all(ok for ok, _ in verdicts.values())

    detected = [f for f in faults if f.protects]
    late = [f for f in faults if f.is_late]
    residual = [f for f in faults if f.is_residual]
    by_class: dict[str, list[Fault]] = defaultdict(list)
    for fault in faults:
        by_class[fault.fault_class].append(fault)

    lines = [
        "# Fault coverage report",
        "",
        "Generated by the campaign. Do not edit by hand.",
        "",
        "## Scope of this number",
        "",
        "This reports **detection coverage over the injected fault set**: of the "
        "faults in this catalog, how many the design detects, and how quickly. "
        "It is **not** diagnostic coverage in the ISO 26262 sense, which requires "
        "an FMEDA with component failure rates in FIT. There are none here, so no "
        "such figure is derivable and none is claimed.",
        "",
        "All latencies are in **simulation steps**. The device advances in "
        "discrete steps and its thermal time scale is deliberately compressed, "
        "so these do not convert to seconds.",
        "",
        "## Summary",
        "",
        f"- Faults injected: **{len(faults)}**",
        f"- Detected within budget: **{len(detected)}**",
        f"- Detected but OUTSIDE budget: **{len(late)}**",
        f"- Known residual: **{len(residual)}**",
        f"- Verdicts met: **{sum(1 for ok, _ in verdicts.values() if ok)} / {len(faults)}**",
        "",
        "## By fault class",
        "",
        "| Class | Injected | Detected in time | Detected late | Residual |",
        "|---|---|---|---|---|",
    ]
    for cls in sorted(by_class):
        group = by_class[cls]
        res = [f for f in group if f.is_residual]
        lt = [f for f in group if f.is_late]
        lines.append(f"| {cls} | {len(group)} | {len(group) - len(res) - len(lt)} "
                     f"| {len(lt)} | {len(res)} |")

    lines += [
        "",
        "## Detection and latency",
        "",
        "| Fault | Class | Challenges | Safe state | Latency | FTTI | Verdict |",
        "|---|---|---|---|---|---|---|",
    ]
    for fault in faults:
        result = results[fault.id]
        ok, why = verdicts[fault.id]
        latency = "n/a" if fault.is_residual else (
            str(result.detected_at_step) if result.detected_at_step else "0 (rejected)")
        budget = "n/a" if fault.ftti_steps is None else str(fault.ftti_steps)
        lines.append(
            f"| {fault.id} | {fault.fault_class} | {', '.join(fault.challenges)} "
            f"| {result.final_state} | {latency} | {budget} "
            f"| {'PASS' if ok else 'FAIL'}: {why} |"
        )

    lines += [
        "",
        "## Residual faults",
        "",
        "Catalogued deliberately. A campaign reporting complete detection would "
        "not be credible, and a gap that is named can be argued about, designed "
        "against or accepted. A gap that is absent from the report cannot.",
        "",
    ]
    for fault in residual:
        lines += [f"### {fault.id}: {fault.title}", "",
                  f"- **Class:** {fault.fault_class}",
                  f"- **Challenges:** {', '.join(fault.challenges)}",
                  f"- **Observed:** {results[fault.id].notes or 'undetected, as documented'}",
                  f"- **Why it cannot be closed here:** {fault.residual_rationale}", ""]

    lines += ["## Requirements not satisfied by this design", ""]
    # Universal claim: one unhandled challenge falsifies it. See traceability.
    unsatisfied = [req for req in requirements
                   if not all(by_id[i].protects for i in mapping[req.id])]
    if unsatisfied:
        lines.append("At least one fault challenging each of these is either "
                     "undetected or detected outside its budget. A requirement "
                     "quantifies over every way it can be broken, so one "
                     "unhandled challenge is enough to leave it unmet:")
        lines.append("")
        for req in unsatisfied:
            lines.append(f"- **{req.id}**: {req.text}")
    else:
        lines.append("None: every fault challenging every requirement is "
                     "detected inside its budget.")
    lines.append("")

    return "\n".join(lines), all_ok


def protection_markdown(faults: tuple[Fault, ...], bare: dict[str, RunResult],
                        protected: dict[str, ProtectedResult]) -> str:
    """What the protection layer bought, fault by fault, under each profile.

    Deliberately a COMPARISON rather than a pass list. "The protection layer
    detects 8 of 8 communication faults" is a true sentence that tells a reader
    nothing, because the bare protocol already detected 7 of them. The number
    that matters is how much earlier, and which one it changed from undetected to
    detected.
    """
    comms = [f for f in faults if f.fault_class == "communication"]

    lines = [
        "# Communication faults with and without the protection layer",
        "",
        "Generated by the campaign. Do not edit by hand.",
        "",
        "One CRC plus counter plus timeout implementation, configured as AUTOSAR "
        "E2E and as PROFIsafe, run against the same eight communication faults as "
        "the bare protocol. See `docs/STANDARDS_MAPPING.md` for the vocabulary, "
        "and note that this models the mechanism rather than implementing either "
        "standard.",
        "",
        "Latency is in **exchanges** for the protected runs and in **steps** for "
        "the bare runs. They are the same unit here, one command per step, but "
        "they are named differently because they are counted at different layers.",
        "",
        "| Fault | Bare protocol | E2E | PROFIsafe | What the layer bought |",
        "|---|---|---|---|---|",
    ]

    for fault in comms:
        b = bare[fault.id]
        bare_cell = ("not detected" if not b.detected
                     else f"step {b.detected_at_step}" if b.detected_at_step
                     else "rejected on arrival")
        cells = []
        for key in ("e2e", "profisafe"):
            r = protected[f"{fault.id}/{key}"]
            cells.append(f"{r.status} @ {r.detected_at}" if r.detected else "**not detected**")

        # The gain is accumulated from independent observations rather than
        # picked from a chain of elif. A fault can both close a gap and reveal a
        # disagreement between the profiles, and a chain would report only
        # whichever happened to be tested first.
        e2e = protected[f"{fault.id}/e2e"]
        ps = protected[f"{fault.id}/profisafe"]
        notes: list[str] = []
        if not b.detected and e2e.detected:
            notes.append("closes a fault the bare protocol never detects")
        if e2e.detected != ps.detected:
            notes.append("**the two profiles disagree**, see below")
        if b.detected_at_step and e2e.detected_at and e2e.detected_at < b.detected_at_step:
            notes.append(f"detected {b.detected_at_step - e2e.detected_at} steps "
                         f"earlier, before the payload reaches the device")
        gain = "; ".join(notes) or "nothing: the bare protocol already rejected it on arrival"
        lines.append(f"| {fault.id} | {bare_cell} | {cells[0]} | {cells[1]} | {gain} |")

    lines += [
        "",
        "## Where the two profiles disagree, and why",
        "",
        "FLT-C08 is a correctly formed, correctly checksummed reply about the "
        "wrong quantity. Neither a CRC nor a sequence counter can catch it: "
        "nothing is corrupted and nothing is out of order.",
        "",
        "**E2E detects it.** A Data ID identifies a *data element*, so a reply "
        "carrying a temperature has a different Data ID from one carrying a "
        "speed, and the mismatch is visible.",
        "",
        "**PROFIsafe does not.** An F_Destination_Address identifies a *device*. "
        "Every message on the link to that device carries the same address, so a "
        "reply about the wrong quantity from the right device passes every check.",
        "",
        "The two mechanisms are routinely presented as equivalent, and for "
        "corruption, repetition, loss and delay they are. For binding a reply to "
        "the question it answers they are not, and the difference is a property "
        "of what the identifier identifies rather than of how strong it is. "
        "Closing it under PROFIsafe is an application layer job.",
        "",
    ]
    return "\n".join(lines) + "\n"


def dual_point_markdown(pairs: tuple[Pair, ...],
                        results: dict[str, PairResult]) -> str:
    """The latent fault report: what a pair did, and what each member did alone.

    All three runs are shown together because a latent fault is DEFINED by the
    difference between them. A table of combined outcomes alone would let a
    reader mistake a latent fault for a primary one that happens to be severe,
    and would hide the control cases entirely.
    """
    lines = [
        "# Latent fault plus primary fault",
        "",
        "Generated by the campaign. Do not edit by hand.",
        "",
        "The single fault campaign asks what the design detects. This one asks "
        "the question a two channel design actually turns on: **what happens "
        "when one channel has been quietly dead for a month.**",
        "",
        "A latent fault violates no safety goal by itself and is not detected, "
        "so nothing announces it. What it does is silently remove a safety "
        "mechanism that only matters later. Each row therefore shows the pair "
        "AND both members alone, because the difference is the finding.",
        "",
        "| Pair | Latent | Primary | Primary alone | Combined | Verdict |",
        "|---|---|---|---|---|---|",
    ]
    for pair in pairs:
        result = results[pair.id]
        alone = ("detected" if result.primary_alone.detected else "undetected")
        alone += f", {result.primary_alone.true_temperature_c:.0f} C"
        combined = ("detected" if result.combined.detected else "**undetected**")
        combined += f", {result.combined.true_temperature_c:.0f} C"
        ok, why = verdict_pair(pair, result)
        lines.append(
            f"| {pair.id} | {pair.latent} | {pair.primary} | {alone} | {combined} "
            f"| {'PASS' if ok else 'FAIL'}: {why} |"
        )

    violated = [p for p in pairs if p.expects_violation]
    lines += [
        "",
        f"**{len(violated)} of {len(pairs)} pairs violate a safety goal that "
        f"neither member violates alone.**",
        "",
        "## Why the control cases are here",
        "",
        "DP-03 and DP-04 pair the same latent fault with primaries the design "
        "handles anyway, and they must come out unchanged. A latent fault that "
        "changed every outcome would not be latent, it would just be a fault, "
        "and without these rows the campaign would read as \"everything gets "
        "worse when you add a second fault\", which is both true and useless.",
        "",
        "## What each pair says",
        "",
    ]
    for pair in pairs:
        lines += [f"### {pair.id}: {pair.title}", "",
                  f"- **Expectation:** {pair.expectation}",
                  f"- **Challenges:** {', '.join(pair.challenges)}",
                  f"- {pair.rationale}", ""]

    lines += [
        "## Scope, so this is not read as more than it is",
        "",
        "Pairs only. Two faults can be attributed, because the pair can be "
        "compared against each member run alone and the difference is caused by "
        "the combination. Beyond two that attribution disappears.",
        "",
        "This is **not** an ISO 26262 latent fault metric. That is a quantity "
        "over a real hardware architecture with failure rates in FIT, and there "
        "are none here. What this measures is whether specific catalogued "
        "combinations defeat the design, which is a statement about these four "
        "pairs and nothing wider.",
        "",
    ]
    return "\n".join(lines) + "\n"
